services:
  hws_database:
    image: 'postgres:17.10'
    restart: always
    environment:
      - 'POSTGRES_DB=hws_db'
      - 'POSTGRES_PASSWORD_FILE=/run/secrets/pg_password'
      - 'POSTGRES_USER_FILE=/run/secrets/pg_username'
    ports:
      - '5432:5432'
    secrets:
      - pg_username
      - pg_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  hws_backend:
    profiles:
      - production
    build:
      context: .
      dockerfile: ./Dockerfile
    secrets:
      - pg_username
      - pg_password
    ports:
      - 8080:8080

secrets:
   pg_password:
     environment: HWS_DEFAULT_PWD
   pg_username:
     environment: HWS_DEFAULT_USER

volumes:
  postgres-data:
