spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hws_db
    username: ${HWS_DEFAULT_USER:parent}
    password: ${HWS_DEFAULT_PWD:hwsParent}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  docker:
    compose:
      enabled: false

logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
      hws:
        home-web-studio: DEBUG
    org:
      springframework:
        security: DEBUG
        security.web: TRACE


org:
  springframework:
    boot:
      autoconfigure:
        jdbc: DEBUG
